### PR TITLE
Update RustCui.cs

### PR DESCRIPTION
**Pull request by Calytic**
More Add/Destroy operations
Should be backwards compatible
Note: have not tested
Slight fix

### CODE REVIEW

**Comment by lukespragg** [comment]
As far as I know, there isn't any point in these since the CUI is only initialized when the player actually exists, so there's no point in having methods for connection.

**Comment by Calytic** [comment]
Sadface.  The point was to refactor the helper to allow people such as myself shortcut methods to AddUI/RemoveUI without having to convert everything to CUIelements or use Facepunch ObjectLists in our own code.

The connection argument isnt important, the new signatures allow us to primarily use json/name strings (more similar to how it works by default) rather than force people to use the CUIElement system.

**Comment by lukespragg** [comment]
Hmmm, I'll pass it by @Nogrod and @bawNg again and see what they think.

**Comment by lukespragg** [comment]
@Nogrod made a change in PR #569, though we feel that the connection overloads aren't needed. Let us know if that's enough for you.

**Pull request closed without merging**
