### PR TITLE
[Rust] Community UI classes

### PR DESCRIPTION
**Pull request by Nogrod**
- Helper & UI Type classes
- no json handling needed

### CODE REVIEW

**Comment by Calytic** [comment]
Could you add the ability to import these controls from json?

**Comment by lukespragg** [comment]
Import them how @Calytic?

**Comment by Calytic** [comment]
Well, he already has an export function that generates JSON from the CUI controls and components.  IMO it would be useful to import these instanced controls/components from JSON, not just export.  That way, if I already have extensive GUI JSON templates built, I can just plug it into CUI rather than having to write a bunch of C# boilerplate and essentially having to do the same thing over except with C#.

**Comment by lukespragg** [comment]
The latest builds should have that now @Calytic. :)

**Pull request merged**
