### PR TITLE
SE WIP

### PR DESCRIPTION
**Pull request by JimLess**
I realy want help, but i need some help here with pull requests...

I make some works for integration.
For silent commands(hidden from all others players), need install workshop mod id 908585300 on server.
source code for client side:
[CODE]using Sandbox.ModAPI;
using System;
using VRage.Game;
using VRage.Game.Components;

namespace Oxide
{
    [MySessionComponentDescriptor(MyUpdateOrder.BeforeSimulation)]
    public class ClientSide : MySessionComponentBase
    {
        public static bool Inited { get; private set; }
        public static bool IsServer { get; private set; }

        private int Frame;

        void Init()
        {
            IsServer = MyAPIGateway.Multiplayer.IsServer || MyAPIGateway.Session.OnlineMode == MyOnlineModeEnum.OFFLINE;
            MyAPIGateway.Utilities.MessageEntered += ChatMessageEntered;
            Inited = true;
        }

        protected override void UnloadData()
        {
            if (Inited)
                MyAPIGateway.Utilities.MessageEntered -= ChatMessageEntered;
        }

        public override void UpdateBeforeSimulation()
        {
            if (MyAPIGateway.Session == null || MyAPIGateway.Utilities == null || MyAPIGateway.Multiplayer == null) // exit if api is not ready
                return;

            if (!Inited)
                Init();
        }

        public static void ChatMessageEntered(string messageText, ref bool sendToOthers)
        {
            if (!messageText.StartsWith("/", StringComparison.OrdinalIgnoreCase))
                return;
            MyAPIGateway.Multiplayer.SendMessageToServer(0xff20, System.Text.Encoding.Unicode.GetBytes(MyAPIGateway.Session.Player.SteamUserId + "," + messageText));
            sendToOthers = false;
        }
    }
}
[/CODE]

### CODE REVIEW

**Comment by lukespragg** [comment]
Getting closer! There's a good bit of unneccesary changes though, and some that do not follow the naming of existing game extensions.

**Comment by JimLess** [comment]
Could you help me? That this is not so, well, or at least for an example to correct my mistakes and show them. I would have done everything right, but I do not know how.

**Comment by lukespragg** [comment]
I'm working through your changes right now locally.

**Comment by JimLess** [comment]
thank u, very much!

**Comment by lukespragg** [comment]
I've got a lot of what you had, with some changes and corrections. I'm debating if IMyPlayer should be used though, as MySession has a lot more useful things and you can access IMyPlayer from MySession too, but I'm not sure it's that easy the other way around.

**Comment by lukespragg** [comment]
Most of this is available now in develop and soon to be master. Still a few things to do. Let me know if you have any issues.

**Pull request closed without merging**
