### PR TITLE
[TheForest] FIXED covalence for TheForest v0.62

### PR DESCRIPTION
**Pull request by netzulo**
### Step 1: Describe the changes

- **Describe the purpose of your changes.** : let covalence load all player data for allow users develop plugins on **TheForest**
- **Describe any known issues or limitations with your changes.** : all this issues was opened by this bug

  + #1135
  + #1131
  + #1110
  + #1105
  + #1104
  + #1091 
  + #1081

### Step 2: Review the checklist

Please use the checklist that is most closely related to your Pull Request _(you only need to use one checklist, and you can skip items that aren't applicable or don't make sense)_:

- [ ] Ensure that the changes compile and match the formatting conventions and standards used
- [ ] Update or add passing unit tests to cover the changes introduced
- [ ] Update or add any necessary API documentation [Documentation Pull Request #62](https://github.com/OxideMod/Docs/pull/62)

### Step 3: Documentation

[https://github.com/OxideMod/Docs/pull/62](https://github.com/OxideMod/Docs/pull/62)

-----

### CODE REVIEW

**Comment by lukespragg** [comment]
Thanks for the work, but this makes some unnecessary changes. I'll make some of the noted changes manually with the changes I have locally. The OnPlayerConnected hook also needs to be properly fixed, not called again from another hook.

**Comment by netzulo** [comment]
Really thank you @lukespragg  , but please, merge documentation, players really need it, wrote about server creation and configuration, so many people asking for this on forums, now we can redirect them to some real place :)

Now i can submit changes so.. will expect your new version learning your code on other games and will propose more changes soon.

PD: im playing server with commands now ! 🥇

**Comment by lukespragg** [comment]
The current API docs aren't intended to have tutorials, just info on using the API provided by Oxide. We do have a forum section that provides Guides & Tips for that sort of thing.

Also, I do have command handling mostly implemented locally.

**Comment by netzulo** [comment]
No problem.. i love forks xD but for **Alpha TheForest** will be good have included this small guidelines to create new Oxide server and start it. How you want it ^^

**Pull request closed without merging**
