### PR TITLE
[Core] Added Remote Console Support

### PR DESCRIPTION
**Pull request by austinv900**
This will allow my remote rcon extension to hook into oxides Root Logger and Console System while still keeping everything sandboxed.

Test For Hurtworld

### CODE REVIEW

**Comment by austinv900** [comment]
As per @lukespragg request the RemoteConsole service has been internalized into Oxide.Core

**Comment by lukespragg** [comment]
Some of the changes such as those in the first commit are and the standalone config file are unnecessary. Any config options can be added to oxide.config.json.

**Comment by austinv900** [comment]
Indeed I just wasn't to sure how you do your config since oxide doesn't seem to load if there is no config present. Is it just adding the files to the ConfigFile.cs in the configuration folder?

**Comment by austinv900** [comment]
I guess I actually mean OxideConfig.cs

**Comment by austinv900** [comment]
@lukespragg Please tell me of I Implemented the config file correctly?

**Comment by austinv900** [comment]
And for the substitute for the event handler in the ServerConsole class I can call the RCON method directly? or do you have another Idea. I thought using the event would be a added feature for any plugin developers that want to implement any kind of Console message outputs into their plugins since anyone can subscribe to it?

**Comment by lukespragg** [comment]
I'll get back to you once @mughisi and I have discussed it a bit more.

**Comment by austinv900** [comment]
Sounds good :)

**Comment by austinv900** [comment]
Was something wrong or deciding against rcon support?

**Comment by lukespragg** [comment]
@austinv900, merged in manually which you can see in the commit above.

**Comment by austinv900** [comment]
I saw that :) I plan on adding in a couple rcon specific commands for RustAdmin.

vFloyd is already aware I was working on it. He would be pleased when I show him the merge request.

**Pull request closed without merging**
