### PR TITLE
Adjusted IModifyTags to try and prevent Modded and Oxide server tags being removed by plugins.

### PR DESCRIPTION
**Pull request by squarefanatic**

### CODE REVIEW

**Comment by lukespragg** [comment]
Thanks for the PR, but I've already got this and a few other changes to these locally. :)

**Comment by squarefanatic** [comment]
Ahh excellent news. Thanks for letting me know. Keen to see the implementation.

**Comment by lukespragg** [comment]
For plugins, they just don't have hooks to use anymore. IModifyTags is internal and hasn't been callable for a few months now, and BuildServerTags is removed. It's not actually an issue with plugins though, custom builds are the ones you see with the tags removed most of the time.

**Comment by squarefanatic** [comment]
I was hoping to use IModifyTags to catch the missing tags on the way back, but removing the functionality all together from the plugins is an excellent next step. Appreciate the feedback and notes. Cheers.

**Comment by lukespragg** [comment]
Pretty sure that adding them back wouldn't help, as the plugin called right after it would just remove them again. Either way, not really possible via plugins anymore, but custom builds are still a thing.

**Pull request closed without merging**
