### PR TITLE
[TheForest] Fix for #1140

### PR DESCRIPTION
**Pull request by netzulo**
### Step 1: Describe the changes

- **Describe the purpose of your changes.** 

+ Fix **TheForestPlayer** constructor
+ Fix **PlayerConnected** to notify all covalence players lists

- **Describe any known issues or limitations with your changes.** 
 
+ Fix for login #1140
+ Fix for logout : _not opened issue_
+ Fix for use commands: _not opened issue_

### Step 2: Review the checklist

- [x] Ensure that the changes compile and match the formatting conventions and standards used
- [x] Update or add passing unit tests to cover the changes introduced
- [x] Update or add any necessary API documentation

### CODE REVIEW

**Comment by netzulo** [comment]
^^ working on #1142 , but ill be better if you can explain how to want to develop , can email me ? ^^ netzuleando@gmail.com

**Comment by netzulo** [comment]
3 commits , 3 break events for all game xD

**Comment by lukespragg** [comment]
Not all 3 commits are needed, Covalence handling is the same for each game we support; it isn't unique in The Forest. I'll manually merge the portions that are relevant.

**Comment by lukespragg** [comment]
Actually, you are right. :P  The newer format that I was updating to did get part of it missed. I'll manually add those changes without the formatting changes, thanks. :)

**Pull request closed without merging**
