### PR TITLE
Hook OnEnterBearTrap

### PR DESCRIPTION
**Pull request by entrailz**
void OnEnterBearTrap(BearTrap trap, GameObject obj)
{
      //Check what kind of object the GameObject is, cast to player etc.
}

### CODE REVIEW

**Comment by Mughisi** [comment]
The injection index to use there should actually be 4. 
And I actually think a better method to hook for this would probably be BearTrap.DelayedFire() after Fire() is called.

**Comment by entrailz** [comment]
My apologies for injection index 6, didn't realise 4 also worked.

Reason for hooking at this point is so I could grab the obj that enters it, as from DelayedFire() it only accesses itself (thinking about it now, could just do this.hurtTarget to get the player.

Maybe you could enlighten how I would reference this.hurtTarget from DelayedFire() while hooking?

Thanks.

**Comment by Mughisi** [comment]
OnTrapTrigger(BearTrap trap) as internal hook, and in RustCore you grab the hurtTarget with reflection and calling the hook OnTrapTriggered(BearTrap trap, GameObject target) or something similar.

**Comment by lukespragg** [comment]
Pokes @Mughisi

**Comment by lukespragg** [comment]
Added manually in next snapshot. Thanks!

**Pull request closed without merging**
