### PR TITLE
Oxide.Tests fix & Config.Get<T> fix

### PR DESCRIPTION
**Pull request by zakharovg**
fixed Config.Get<T> method when using with ValueType. Covered with tests.
Fixed existing tests in Oxide.Tests

### CODE REVIEW

**Comment by zakharovg** [comment]
Was not sure you need those tests are not, but decided to fix them anyway.

**Comment by lukespragg** [comment]
Some of this is okay, but I wouldn't merge all of it. The DLLs don't really need to be duplicated either, that just adds bloat to the repo. It'll likely get cherry picked.

**Comment by zakharovg** [comment]
The DLLs are in to make Lua tests running, other tests do not require them. Would be better to add them as nuget package, if possible. Could you give more details on parts of the code you don't like?

**Comment by zakharovg** [comment]
Merged with latest master and added support for custom classes in config.get<>. Be sure to check the tests and tell if there should be more tests/cases.

**Comment by AdamChandler** [comment]
@lukespragg Everything looks good and I see no problem with merging all the changes. Adding of the dlls is also fine because it fix's failed references.

**Comment by lukespragg** [comment]
The tests can use the existing DLLs, ex. https://github.com/OxideMod/Oxide/tree/master/Oxide.Ext.Lua/Dependencies.

**Comment by lukespragg** [comment]
Merged manually with some tweaks, thanks!

**Pull request closed without merging**
