### PR TITLE
Update OxideMod.cs

### PR DESCRIPTION
**Pull request by Calytic**
Proposed fix for http://oxidemod.org/threads/trouble-reading-my-custom-config.20846/

### CODE REVIEW

**Comment by Mughisi** [comment]
When a plugin is added it loads the config here https://github.com/OxideMod/Oxide/blob/develop/Oxide.Core/Plugins/Plugin.cs#L172
There might be something else going on in that thread.

**Comment by Calytic** [comment]
Is LoadDefaultConfig called after Loaded?  If so, then that would explain why.

**Comment by lukespragg** [comment]
The configuration file is only loaded once with LoadDefaultConfig. If the user modified what is generated after the file was created, it won't be called again if the file already exists.

**Comment by Calytic** [comment]
1. Load Test.cs
2. Run test.test
3. Expected Result: Random Item from list

**Comment by Mughisi** [comment]
Had another look @Calytic and it does in fact result in the given error. It seemed that the call to load the config file was only executed when the config file already existed so I have reworked LoadDefaultConfig() to always load the file. https://github.com/OxideMod/Oxide/commit/60e8e74ffbd94a5bfa1025ffe99c3bcc938b55c3

**Pull request closed without merging**
